import React from 'react';
import { Link } from 'react-router-dom';
import { 
  Activity, 
  Brain, 
  LineChart, 
  ShieldAlert, 
  Sparkles, 
  ArrowRight,
  TrendingUp,
  Heart,
  Droplet
} from 'lucide-react';

export default function Home() {
  const features = [
    {
      title: 'Biometric Analytics',
      desc: 'Log body stats, heart rate, hydration indices, sleep patterns, and caloric balance.',
      icon: Activity,
      color: 'text-primary bg-primary/10 border-primary/20'
    },
    {
      title: 'AI Diagnostic Score',
      desc: 'Our real-time prediction model analyzes your vitals to compute a comprehensive daily Health Score.',
      icon: Brain,
      color: 'text-indigo-600 bg-indigo-50 border-indigo-100'
    },
    {
      title: 'Dynamic Recommendations',
      desc: 'Get highly personalized, immediate workout, diet, and recovery plans calculated on your daily log.',
      icon: Sparkles,
      color: 'text-emerald-600 bg-emerald-50 border-emerald-100'
    },
    {
      title: 'Historical Trends',
      desc: 'Track health metrics over time with interactive graphs, averages, and targets milestone achievements.',
      icon: LineChart,
      color: 'text-amber-600 bg-amber-50 border-amber-100'
    }
  ];

  return (
    <div className="space-y-24 py-12 relative overflow-hidden">
      {/* Background decoration elements */}
      <div className="absolute top-20 left-10 w-72 h-72 bg-primary/5 rounded-full filter blur-[100px] pointer-events-none" />
      <div className="absolute bottom-20 right-10 w-96 h-96 bg-emerald-500/3 rounded-full filter blur-[120px] pointer-events-none" />

      {/* Hero Section */}
      <section className="relative text-center max-w-4xl mx-auto px-4 space-y-8">
        {/* Decorative Badge */}
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-50 border border-slate-200 text-xs font-semibold text-slate-600">
          <Sparkles className="w-3.5 h-3.5 text-primary animate-pulse" />
          <span>Next-Generation AI Health Metrics</span>
        </div>

        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight leading-tight md:leading-none text-slate-800 font-display">
          Track Your Vitals. <br />
          Unlock <span className="text-gradient">AI Predictions.</span>
        </h1>

        <p className="text-lg md:text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed">
          Monitor daily biometrics, get real-time health risk scoring, and receive immediate, actionable lifestyle directives generated by our local prediction engine.
        </p>

        <div className="flex flex-col sm:flex-row justify-center gap-4 pt-4">
          <Link to="/signup" className="btn btn-primary text-base px-8 py-3.5 flex items-center gap-2 group">
            <span>Get Started Free</span>
            <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
          </Link>
          <Link to="/login" className="btn btn-outline text-base px-8 py-3.5">
            Access Dashboard
          </Link>
        </div>
      </section>

      {/* Interactive Mock UI Preview */}
      <section className="relative max-w-5xl mx-auto px-4 animate-in fade-in slide-in-from-bottom-10 duration-1000">
        <div className="glass p-4 md:p-6 shadow-xl relative">
          {/* Mock UI window bar */}
          <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-6">
            <div className="flex gap-2">
              <span className="w-3 h-3 rounded-full bg-rose-500/60" />
              <span className="w-3 h-3 rounded-full bg-amber-500/60" />
              <span className="w-3 h-3 rounded-full bg-emerald-500/60" />
            </div>
            <span className="text-xs text-slate-400 font-mono">dashboard_mockup.json</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 flex items-center gap-3">
              <Heart className="w-8 h-8 text-rose-500 animate-pulse" />
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-500">Health Risk Score</span>
                <p className="text-xl font-bold text-slate-800 mt-0.5">92 / 100</p>
              </div>
            </div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 flex items-center gap-3">
              <TrendingUp className="w-8 h-8 text-primary" />
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-500">BMI Classification</span>
                <p className="text-xl font-bold text-slate-800 mt-0.5">Normal Weight (22.5)</p>
              </div>
            </div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 flex items-center gap-3">
              <Droplet className="w-8 h-8 text-sky-500" />
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-500">Hydration Index</span>
                <p className="text-xl font-bold text-slate-800 mt-0.5">Optimal (2.8 L)</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid Section */}
      <section className="max-w-6xl mx-auto px-4 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-800 font-display">Core Application Capabilities</h2>
          <p className="text-slate-500 max-w-xl mx-auto text-sm">
            Everything you need to gather biometric logs and understand metrics in one local, hyper-responsive workspace.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feat, idx) => {
            const Icon = feat.icon;
            return (
              <div 
                key={idx} 
                className="glass p-6 border border-slate-100 hover:border-slate-200 hover:shadow-lg transition-all duration-300 flex flex-col justify-between group"
              >
                <div className="space-y-4">
                  <div className={`w-12 h-12 rounded-xl flex items-center justify-center border ${feat.color}`}>
                    <Icon className="w-6 h-6 transition-transform group-hover:scale-110" />
                  </div>
                  <h3 className="text-lg font-bold text-slate-800 font-display">{feat.title}</h3>
                  <p className="text-slate-500 text-xs leading-relaxed">{feat.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Trust / Call To Action Banner */}
      <section className="max-w-4xl mx-auto px-4">
        <div className="glass p-8 md:p-12 border border-slate-100 relative overflow-hidden text-center space-y-6">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-primary/10 rounded-full filter blur-[80px]" />
          
          <h2 className="text-2xl md:text-3xl font-bold text-slate-800 font-display relative z-10">
            Take Control of Your Fitness Metrics Today
          </h2>
          
          <p className="text-sm text-slate-500 max-w-lg mx-auto relative z-10">
            Create a free local account in seconds. All metrics calculations run locally on your system, keeping your biometric data private and secure.
          </p>

          <div className="relative z-10 pt-2">
            <Link to="/signup" className="btn btn-primary px-8 py-3">
              Create Free Account
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
